// Prompt builders. buildReviewPrompt is a faithful port of build_prompt_file in
// pr-review-bot.sh. buildVisualizationPrompt is new: it asks for a single self
// contained HTML document that helps a human reviewer see what changed.

export function buildReviewPrompt(params: {
  repo: string;
  pr: number;
  title: string;
  overview?: string;
  changedFiles?: string;
  hasCheckout?: boolean;
  append?: string;
}): string {
  const { repo, pr, title, overview, changedFiles, hasCheckout, append } = params;
  const parts: string[] = [];
  const explore = hasCheckout
    ? "You are in a checkout of the repository at this PR's head commit, so use your read/grep/find/ls tools to explore ANY committed file for context, not just changed files. The checkout contains ONLY the repository's committed files: installed dependencies (.venv, node_modules, vendored packages) are NOT present, so reason about third-party libraries from their usage and public docs rather than trying to read their source."
    : "No local checkout is available, so review from the diffs and PR context alone.";
  parts.push(`You are reviewing GitHub pull request #${pr} in ${repo}
(https://github.com/${repo}/pull/${pr}).

FIRST, before reviewing any file: use the read tool to open every required skill or context file named by the system prompt or Additional instructions. Follow that guidance for the rest of this review. PR diff tools and submit_review are blocked until the required context has been read.

${explore}

Review the PR using these tools (do not output JSON):
- The changed files are listed below. After required context has been read, review them in whatever order is most effective (e.g. group related files, start with the riskiest) using pr_file_diff(path). Only RIGHT-side (new file) lines shown in a diff are commentable.
- Call review_status() any time to see which files you have and have not reviewed. next_pr_file() will hand you an arbitrary remaining file if you just want to mop up.
- You MUST review every changed file's diff before finishing.
- Log each issue with add_suggestion({ path, line, startLine?, body }), as you review or before submitting. It validates the anchor and flags non-commentable lines so you can fix them.
- Prefer GitHub commit suggestions whenever there is a safe concrete replacement: include a fenced \`\`\`suggestion block in the suggestion body. Use a plain comment only for conceptual issues, missing tests, questions, or fixes that cannot be expressed as an exact replacement.
- Once every file is reviewed (check with review_status) and any cross-file issues are added, call submit_review({ decision, summary }) to finish.

Rules:
- Use decision "approve" ONLY when there are no major or blocking issues (and add no suggestions). Otherwise use "suggestions".
- On "approve", the "summary" MUST start with "lgtm" (lower case). Do not use filler praise like "nice and clean" or "looks great"; keep it to "lgtm" optionally followed by one short factual clause.
- line/startLine are NEW-version (RIGHT side) line numbers from the diff hunk headers. For a multi-line region set startLine < line, both in the SAME hunk; omit startLine for single-line notes.
- Every suggestion body and the summary must be plain, friendly, peer-toned (e.g. "Consider ...", "Might be cleaner to ..."), 1-3 sentences. A suggestion body may add one GitHub suggestion fence after the prose when it provides an exact replacement.
- Do NOT mention AI, models, tools, or attribution. No emojis. No em-dashes. No "generated by" footers.
- Do NOT reproduce or echo file contents, hashes, tokens, keys, base64, or long strings. Refer to code by path and line only.`);

  if (append && append.trim() !== "") {
    parts.push(`\nAdditional instructions:\n${append}`);
  }

  if (changedFiles && changedFiles.trim() !== "") {
    parts.push(`\nChanged files:\n${changedFiles}`);
  }

  parts.push(`\nPR title: ${title}`);
  if (overview && overview.trim() !== "") {
    parts.push(`\nPR overview:\n${overview}`);
  }
  parts.push("\nStart now: read any required skill/context files first. Then pick the file you want to review first and call pr_file_diff(path).");
  return parts.join("\n");
}

export function buildVisualizationPrompt(params: {
  repo: string;
  pr: number;
  title: string;
  body: string;
  diff: string;
}): string {
  const { repo, pr, title, body, diff } = params;
  return `You convert a GitHub pull request diff into a JSON spec for a change
visualization that a reviewer can scan at a glance. You are given ONLY the
unified diff and PR context below.

Output rules:
- Output ONLY a single JSON object. No markdown fences, no commentary, no prose.
- The visualization must consist purely of charts, diagrams and tables. Never
  output sentences, paragraphs, summaries, rationale or explanations. Use only
  short labels, column names and numbers.
- Every number must be derived from the diff. Do not invent metrics.
- Keep labels short: file paths, area names, categories.

Schema:
{
  "title": string (short, optional),
  "blocks": Block[]
}

Block is one of:
- {"kind":"stats","title":string?,"stats":[{"label":string,"value":number,"unit":string?,"tone":Tone?}]}
- {"kind":"bar","title":string?,"unit":string?,"data":[{"label":string,"value":number,"tone":Tone?}]}
- {"kind":"donut","title":string?,"unit":string?,"data":[{"label":string,"value":number,"tone":Tone?}]}
- {"kind":"treemap","title":string?,"unit":string?,"data":[{"label":string,"value":number,"tone":Tone?}]}
- {"kind":"stacked","title":string?,"unit":string?,"series":string[],"data":[{"label":string,"values":number[]}]}
- {"kind":"heatmap","title":string?,"columns":string[],"rows":string[],"values":number[][],"legend":[string,string]?}
- {"kind":"table","title":string?,"columns":string[],"rows":string[][]}

Tone is one of "neutral","add","del","warning","critical".

Guidance:
- Start with a "stats" block for totals: files, lines added, lines removed.
- Add a "stacked" block of added vs removed per file.
- Add a "donut" or "treemap" for churn grouped by area (source, tests, docs, config).
- Add a "heatmap" for risk by file (rows) across dimensions such as security,
  tests, config, behavior and error handling (columns) using small integer scores.
- Add a "table" of file impact with columns File, Area, Added, Removed, Risk.
- Keep it under 12 blocks and 24 rows/items per block.

Repository: ${repo}
PR number: ${pr}

PR title: ${title}

PR description:
${body}

Unified diff:
${diff}`;
}
