// Prompt builders. buildReviewPrompt is a faithful port of build_prompt_file in
// pr-review-bot.sh. buildVisualizationPrompt is new: it asks for a single self
// contained HTML document that helps a human reviewer see what changed.

export function buildReviewPrompt(params: {
  repo: string;
  pr: number;
  title: string;
  overview?: string;
  hasCheckout?: boolean;
  append?: string;
}): string {
  const { repo, pr, title, overview, hasCheckout, append } = params;
  const parts: string[] = [];
  const explore = hasCheckout
    ? "You are in a checkout of the repository at this PR's head commit, so use your read/grep/find/ls tools to explore ANY file in the repo for context, not just changed files."
    : "No local checkout is available, so review from the diff and PR context alone.";
  parts.push(`You are reviewing GitHub pull request #${pr} in ${repo}
(https://github.com/${repo}/pull/${pr}). Apply the loaded review skills.

${explore}

To see what the PR changes, use these read only tools:
- pr_diff() for the whole PR diff (truncated if very large).
- pr_file_diff(path) for a single changed file's diff. Only lines that appear in a file's diff (RIGHT side) are commentable.
The PR overview (title, description, changed files, commits, existing reviews/comments) is provided below.

Return your review as a SINGLE JSON object and NOTHING ELSE, matching exactly:

{
  "decision": "approve" | "suggestions",
  "summary": "1-2 short friendly sentences",
  "comments": [
    { "path": "relative/file/path", "start_line": <optional first new-side line of the region>, "line": <last new-side line number>, "side": "RIGHT", "body": "1-3 friendly sentences" }
  ]
}

Rules:
- Use "approve" ONLY when there are no major or blocking issues; "comments" is then [].
- On "approve", the "summary" MUST start with "lgtm" (lower case). Do not use filler praise like "nice and clean" or "looks great"; keep it to "lgtm" optionally followed by one short factual clause.
- Use "suggestions" when major or blocking issues exist; include concrete inline comments.
- "line" is the line number in the NEW version of the file (RIGHT side), taken from the diff hunk headers.
- When a suggestion applies to a multi-line region, set "start_line" to the first line and "line" to the last line of that region; both must appear in the SAME diff hunk and "start_line" must be strictly less than "line". Omit "start_line" for genuinely single-line notes.
- Every "body" and the "summary" must be plain, friendly, peer-toned (e.g. "Consider ...", "Might be cleaner to ...").
- Do NOT mention AI, models, tools, or attribution. No emojis. No em-dashes. No "generated by" footers.
- Keep each comment to 1-3 sentences.
- Do NOT reproduce or echo file contents, hashes, tokens, keys, base64, or long strings in your output, and never repeat text. Refer to code by path and line only, and keep the whole response short.
- Every string value MUST be valid JSON: escape newlines as \n and do not put literal line breaks, tabs, or unescaped double quotes inside string values.
- CRITICAL: Output the raw JSON object ONLY. Do NOT wrap it in markdown code fences, and do NOT add any text, explanation, or notes before or after the JSON.`);

  if (append && append.trim() !== "") {
    parts.push(`\nAdditional instructions:\n${append}`);
  }

  parts.push(`\nPR title: ${title}`);
  if (overview && overview.trim() !== "") {
    parts.push(`\nPR overview:\n${overview}`);
  }
  parts.push("\nReview the changes now. Read the changed files in the checkout and their diffs, then produce your verdict.");
  return parts.join("\n");
}

export function buildVisualizationPrompt(params: {
  repo: string;
  pr: number;
  title: string;
  body: string;
  diff: string;
}): string {
  const { repo, pr, title, body, diff } = params;
  return `You are generating a change visualization for GitHub pull request #${pr} in ${repo}.
Produce a SINGLE self contained HTML document that helps a human reviewer quickly
understand what this pull request changes and why it matters. You are given ONLY
the unified diff below.

Output rules:
- Output ONE complete HTML document only, starting with <!doctype html>. No markdown
  fences, no commentary before or after.
- The document must be fully self contained: inline CSS in a <style> tag, no external
  network requests, no remote scripts, fonts, or images.
- Use only solid colors, no CSS gradients. Keep box shadows minimal or absent. Use a
  clean neutral palette that works on a white background.
- No emojis. No em-dashes or en-dashes anywhere in the text.

Content the document should include:
- A short high level summary of what changed and why it matters.
- A file by file impact list: for each touched file, one line on what changed.
- A risk and attention section calling out anything a reviewer should look at closely
  (behavior changes, security, error handling, migrations, config).
- Short annotated snippets for the most important changes, referenced by file and line.
Do not simply re-print the raw diff; interpret it for the reviewer.

PR title: ${title}

PR description:
${body}

Unified diff:
${diff}`;
}

// Extract a single HTML document from model output, tolerant of fences or
// leading prose. Returns null when nothing HTML-like is found.
export function extractHtmlDocument(text: string): string | null {
  let t = text.replace(/```[a-zA-Z]*/g, "").replace(/```/g, "");
  const lower = t.toLowerCase();
  const docStart = lower.indexOf("<!doctype html");
  if (docStart >= 0) return t.slice(docStart).trim();
  const htmlStart = lower.indexOf("<html");
  if (htmlStart >= 0) return t.slice(htmlStart).trim();
  return null;
}
