import { describe, it, expect } from "vitest";
import { sanitizeReviewComment, sanitizeText } from "./sanitize";

describe("sanitizeText", () => {
  it("strips AI attribution phrases", () => {
    expect(sanitizeText("As an AI, consider renaming this")).toBe(
      "consider renaming this",
    );
  });
  it("removes model vendor names", () => {
    expect(sanitizeText("Claude thinks this is fine")).toBe("thinks this is fine");
  });
  it("converts em dashes to hyphens", () => {
    expect(sanitizeText("value\u2014here")).toBe("value-here");
  });
  it("removes co-authored-by trailer", () => {
    expect(sanitizeText("looks good\nCo-authored-by: Claude bot")).toContain(
      "looks good",
    );
    expect(sanitizeText("looks good\nCo-authored-by: Claude bot")).not.toContain(
      "Co-authored-by",
    );
  });
  it("collapses double spaces and trims", () => {
    expect(sanitizeText("  hello   world  ")).toBe("hello world");
  });
  it("strips a generated-by prefix", () => {
    expect(sanitizeText("generated by AI: rename this")).toBe("rename this");
  });
});

describe("sanitizeReviewComment", () => {
  it("preserves indentation inside suggestion fences", () => {
    const input = "As an AI, consider this:\n\n```suggestion\nif (ok) {\n    return value;\n}\n```";
    expect(sanitizeReviewComment(input)).toBe("consider this:\n\n```suggestion\nif (ok) {\n    return value;\n}\n```");
  });

  it("still sanitizes prose around fences", () => {
    const input = "generated by AI: use this 🙂\n\n```suggestion\n  x\n```";
    expect(sanitizeReviewComment(input)).toBe("use this\n\n```suggestion\n  x\n```");
  });
});
